### ISSUE TITLE
Chapter 35.2 Across with filter

### ISSUE THREAD

**Issue by leynu** [brad-cannell/r4epi#39]
Hi, 

"Chapter 35.2 Across with filter" needs to be revised. The reason is that usage of across()` in `filter()` is deprecated. 
For instance, this code in the book
```
df_xyz %>% 
  filter(
    across(
      .cols = everything(),
      .fns  = ~ !is.na(.x)
    )
  )
```
will generate the following message: 
Using `across()` in `filter()` is deprecated, use `if_any()` or `if_all()`.

Kind regards, 
Leyla

**Comment by mbcann01** [comment]
Hi @leynu ,

Thank you very much for pointing this out! I will try to get it corrected soon.

Respectfully,
Brad

**Comment by mbcann01** [comment]
https://www.tidyverse.org/blog/2021/02/dplyr-1-0-4-if-any/

**Comment by mbcann01** [comment]
Left off on line 641. Need to walk through examples of how if_any and if_all work.

**Comment by mbcann01** [comment]
Hi @leynu,

I'm sorry it took me so long to get around to fixing this. I'd love your feedback on the revisions if you get time.

Respectfully,
Brad
